### ISSUE TITLE
Update to the latest version of openDS 4.0

### ISSUE THREAD

**Issue by breznak** [breznak/openDS#17]
which came out during our development, we will have to see what broke or if something is better! :wink:

**Comment by breznak** [comment]
These are current errors when compiling with merged ODS 4.0: 

```
 /mnt/store/devel/driving/openDS2/src/eu/opends/visualization/MovieData.java
    /mnt/store/devel/driving/openDS2/src/eu/opends/visualization/MoviePlayer.java
/mnt/store/devel/driving/openDS2/src/eu/opends/basics/SimulationBasics.java:43: error: cannot find symbol
import com.jme3.util.SkyFactory.EnvMapType;
  symbol:   class EnvMapType
  location: class SkyFactory
/mnt/store/devel/driving/openDS2/src/eu/opends/car/SteeringCar.java:38: error: package eu.opends.simphynity does not exist
import eu.opends.simphynity.SimphynityController;
/mnt/store/devel/driving/openDS2/src/eu/opends/car/SteeringCar.java:60: error: cannot find symbol
    private SimphynityController simphynityController;
  symbol:   class SimphynityController
  location: class SteeringCar
/mnt/store/devel/driving/openDS2/src/eu/opends/main/BinaryConverter.java:32: error: cannot find symbol
import com.jme3.util.SkyFactory.EnvMapType;
  symbol:   class EnvMapType
  location: class SkyFactory
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:35: error: package com.jme3.profile does not exist
import com.jme3.profile.AppProfiler;
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:36: error: package com.jme3.profile does not exist
import com.jme3.profile.AppStep;
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:37: error: package com.jme3.profile does not exist
import com.jme3.profile.VpStep;
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:65: error: cannot find symbol
public class BasicProfiler implements AppProfiler {
  symbol: class AppProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:175: error: cannot find symbol
    public void appStep( AppStep step ) {
  symbol:   class AppStep
  location: class BasicProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:202: error: cannot find symbol
    public void vpStep( VpStep step, ViewPort vp, Bucket bucket ) {
  symbol:   class VpStep
  location: class BasicProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:38: error: cannot find symbol
import com.jme3.app.state.BaseAppState;
  symbol:   class BaseAppState
  location: package com.jme3.app.state
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:58: error: cannot find symbol
public class BasicProfilerState extends BaseAppState {
  symbol: class BaseAppState
/mnt/store/devel/driving/openDS2/src/eu/opends/basics/SimulationBasics.java:393: error: cannot find symbol
                sky = SkyFactory.createSky(assetManager, skyModelPath, EnvMapType.CubeMap);
                                                                       ^
  symbol:   variable EnvMapType
  location: class SimulationBasics
/mnt/store/devel/driving/openDS2/src/eu/opends/basics/SimulationBasics.java:400: error: cannot find symbol
                sky = SkyFactory.createSky(assetManager, skyModelPath, EnvMapType.SphereMap);
                                                                       ^
  symbol:   variable EnvMapType
  location: class SimulationBasics
/mnt/store/devel/driving/openDS2/src/eu/opends/basics/SimulationBasics.java:413: error: cannot find symbol
            sky = SkyFactory.createSky(assetManager, SimulationDefaults.skyTexture, EnvMapType.CubeMap);
                                                                                    ^
  symbol:   variable EnvMapType
  location: class SimulationBasics
/mnt/store/devel/driving/openDS2/src/eu/opends/basics/SimulationBasics.java:420: error: cannot find symbol
            sky = SkyFactory.createSky(assetManager, SimulationDefaults.skyTexture, EnvMapType.CubeMap);
                                                                                    ^
  symbol:   variable EnvMapType
  location: class SimulationBasics
/mnt/store/devel/driving/openDS2/src/eu/opends/main/Simulator.java:327: error: incompatible types: BasicProfilerState cannot be converted to AppState
        stateManager.attach(new BasicProfilerState(false));
                            ^
/mnt/store/devel/driving/openDS2/src/eu/opends/car/SteeringCar.java:141: error: cannot find symbol
            simphynityController = new SimphynityController(sim, this, ip, port);
                                       ^
  symbol:   class SimphynityController
  location: class SteeringCar
/mnt/store/devel/driving/openDS2/src/eu/opends/main/BinaryConverter.java:65: error: cannot find symbol
        Spatial sky = SkyFactory.createSky(assetManager, SimulationDefaults.skyTexture, EnvMapType.CubeMap);
  symbol:   variable EnvMapType
  location: class BinaryConverter
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:174: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:178: error: cannot find symbol
            case BeginFrame:
  symbol:   variable BeginFrame
  location: class BasicProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:181: error: cannot find symbol
            case RenderFrame:
  symbol:   variable RenderFrame
  location: class BasicProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:185: error: cannot find symbol
            case EndFrame:
  symbol:   variable EndFrame
  location: class BasicProfiler
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfiler.java:201: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:74: error: cannot find symbol
        setEnabled(enabled);
  symbol:   method setEnabled(boolean)
  location: class BasicProfilerState
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:79: error: cannot find symbol
        setEnabled(!isEnabled());
  symbol:   method isEnabled()
  location: class BasicProfilerState
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:178: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:207: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:216: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:220: error: cannot find symbol
        setFrameCount(getApplication().getCamera().getWidth());
  symbol:   method getApplication()
  location: class BasicProfilerState
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:222: error: cannot find symbol
        getApplication().setAppProfiler(profiler);
  symbol:   method getApplication()
  location: class BasicProfilerState
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:223: error: cannot find symbol
        Node gui = ((SimpleApplication)getApplication()).getGuiNode();
  symbol:   method getApplication()
  location: class BasicProfilerState
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:228: error: method does not override or implement a method from a supertype
    @Override
/mnt/store/devel/driving/openDS2/src/eu/opends/profiler/BasicProfilerState.java:230: error: cannot find symbol
        getApplication().setAppProfiler(null);
  symbol:   method getApplication()
  location: class BasicProfilerState
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
34 errors
ZipFileIndex clearCache failed
/mnt/store/devel/driving/openDS2/IDEs/netbeans/nbproject/build-impl.xml:941: The following error occurred while executing this line:
/mnt/store/devel/driving/openDS2/IDEs/netbeans/nbproject/build-impl.xml:291: Compile failed; see the compiler error output for details.
    at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1181)
    at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
    at org.netbeans.modules.java.source.ant.JavacTask.execute(JavacTask.java:145)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(Unknown Source)
    at org.apache.tools.ant.module.run.TargetExecutor.run(Unknown Source)
    at org.netbeans.core.execution.RunClassThread.run(Unknown Source)
BUILD FAILED (total time: 5 seconds)

```
